# Generated by Django 3.2.4 on 2021-08-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codigo', '0001_initial'),
        ('orden', '0003_orden_direccion_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='promo_codigo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_codigo.promocodigo'),
        ),
    ]
